name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 项目的主要分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # 项目所需的Node.js版本

    - name: Create .env file
      run: |
        echo "VUE_APP_NAME=${{ secrets.VUE_APP_NAME }}" >> .env
        echo "VUE_APP_GITHUB_USERNAME=${{ secrets.VUE_APP_GITHUB_USERNAME }}" >> .env
        echo "VUE_APP_GITHUB_TOKEN=${{ secrets.VUE_APP_GITHUB_TOKEN }}" >> .env

    - name: Install dependencies
      run: npm install

    - name: Build project
      env:
        VUE_APP_NAME: ${{ secrets.VUE_APP_NAME }}
        VUE_APP_GITHUB_USERNAME: ${{ secrets.VUE_APP_GITHUB_USERNAME }}
        VUE_APP_GITHUB_TOKEN: ${{ secrets.VUE_APP_GITHUB_TOKEN }}
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Vue项目的构建输出目录
